#CRUD : Menampilkan seluruh data produk
GET http://localhost:3000/product

#CRUD : Menampilkan data berdasarkan id
###
GET http://localhost:3000/product/2


#CRUD : menambah data
###
POST http://localhost:3000/product
Content-Type: application/json

{
  "namaproduct":"Kopipo",
  "harga": 1,
  "kategori": "minuman",
  "stok": 8
}

#CRUD : Mengubah data berdasarkan id
###
PATCH http://localhost:3000/product/
Content-Type: application/json

{
  "namaproduct":"",
  "harga":"10000",
  "kategori": "minuman",
  "stok": "20"
}

#CRUD : Menghapus data berdasarkan id
###
DELETE http://localhost:3000/product/6

###

#menampilkan product berdasarkan kategori
GET http://localhost:3000/product/kategori/makanan


#menampilkan produk berdasarkan nama produk dan membatasi berdasarkan harga maksimum
###
GET http://localhost:3000/product/search?nama=kopi&maxHarga=20000

#Soal 3 Validasi dan pengelolaan stok produk
###
PATCH http://localhost:3000/product/2/stok
Content-Type: application/json

{
  "stock" :-0
}


######
#KARYAWAN
#######
GET http://localhost:3000/karyawans/

###
GET http://localhost:3000/karyawans/6


##

###
POST http://localhost:3000/karyawans
Content-Type: application/json

{
  "nomorkaryawan": "000001",
  "namakaryawan": "fadil jaidi",
  "jeniskelamin": "laki-laki",
  "pendidikan": "D3"
}

###
PATCH http://localhost:3000/karyawans/2
Content-Type: application/json

{
  "nomorkaryawan": "00005",
  "namakaryawan": "Taqiyah",
  "jeniskelamin": "Perempuan",  
  "pendidikan": "S1"  
}

###
DELETE http://localhost:3000/karyawans/

###
