######
#KARYAWAN
#######
GET http://localhost:3000/karyawans/

###
GET http://localhost:3000/karyawans/6


##

###
POST http://localhost:3000/karyawans
Content-Type: application/json

{
  "nomorkaryawan": "00005",
  "namakaryawan": "Gyenisa",
  "jeniskelamin": "perempuan",
  "pendidikan": "S3"
}

###
PATCH http://localhost:3000/karyawans/2
Content-Type: application/json

{
  "nomorkaryawan": "00003",
  "namakaryawan": "Rizqon Noval",
  "jeniskelamin": "laki-laki",  
  "pendidikan": "S1"  
}

###
DELETE http://localhost:3000/karyawans/

###
